---
- name: This playbook is used to install the packages
  hosts: all
  become: true
  vars_files:
    - packages.yml
  tasks:
  - name: Update the apt repository
    apt:
      update_cache: yes
  - name: Install the packages
    apt:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
